[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
connection_utils = { path = "../connection_utils" }
tokio = { version = "1", features = ["full"] }
