[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
connection_utils = { path = "../connection_utils" }
serde = "1.0.144"
tokio = { version = "1", features = ["full"] }
